[package]
name = "rltk-tutorial"
authors = ["Keith Sharp <kms@passback.co.uk"]
license = "MIT and AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
rltk = "0.8.0"
specs = "0.18.0"
specs-derive = "0.4.1"